config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
    post :new
  end
  get 'angular-items', to: 'portfolios#angular'

  get 'portfolio/:id', to:'portfolios#show', as: 'portfolio_show'

  get 'about-me', to:'pages#about'
  get 'contact', to:'pages#contact'
  get 'france-info-news', to:'pages#france_info_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for   :technologies,
                                  allow_destroy: true,
                                  reject_if: lambda {|techno_attrs| techno_attrs['name'].blank?}

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  #scope angular:
  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails')}

  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit,:update, :destroy, :show]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |k, v|
      Portfolio.find(v[:id]).update(position: v[:position])
    end

    render body: nil
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio is now live !' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    # destroy it
    @portfolio.destroy
    # redirect to index page
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'the portfolio was successfully removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                     )
  end

  def set_portfolio_item
    @portfolio = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img
      img
    elsif type=='thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height:  '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.full_messages.each do |err| %>
      <%= alert_generator err %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, style:'display:none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= form.file_field :thumb_image, style:'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-8">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr/>

  <div class="col-md-12">
    <h2>Technology used</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f:technology_form %>
      <% end %>
    </div>

    <div>
      <%= link_to_add_association 'Add a technology', form, :technologies %>
    </div>

    <div class="form-group">
      <%= form.submit 'Save Portfolio Item', class:'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4 portfolio-card" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 shadow-sm">
      <%= image_tag portfolio_img(portfolio_item.thumb_image.url, 'thumb'), width: '100%' %>
    <div class="card-body">
      <p class="card-text"><span><%= portfolio_item.title %></span> <%=portfolio_item.subtitle%></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to 'View', portfolio_show_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>ANGULAR Portfolio Items</h1>

<%= link_to "Create a new portfolio", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%=portfolio_item.subtitle%></p>
  <p><%=portfolio_item.body%></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to 'Edit', edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this new portfolio Item</h1>

  <%= render 'form', portfolio_item:@portfolio %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper('alert alert-warning') %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new portfolio Item</h1>

  <%= render 'form', portfolio_item:@portfolio %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio.main_image.url, 'main'), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio.title %></h1>

      <em><%= @portfolio.subtitle %></em>

      <p><%= @portfolio.body %></p>
      <hr/>
      <h3>Technologies Used:</h3>
      <% @portfolio.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
      <% if logged_in?(:site_admin) %>
      <div>
        <%= link_to 'Edit', edit_portfolio_path(@portfolio), class: 'btn btn-warning' %>
      </div>
      <% end %>
    </div>
  </div>
</div>